language: rust
sudo: false

env:
  global:
  - PATH=$HOME/.cargo/bin:$PATH

matrix:
  include:
  - os: linux
    rust: stable
    env: HARFBUZZ_SYS_NO_PKG_CONFIG="0"
  - os: linux
    rust: stable
    env: HARFBUZZ_SYS_NO_PKG_CONFIG="1"
  - os: linux
    rust: nightly
  - os: osx
    rust: stable

before_script:
- git clone --depth 1 https://github.com/rust-lang/cargo.git /tmp/cargo
- cargo install --path /tmp/cargo

script:
#- touch harfbuzz-sys/harfbuzz/{configure.ac,aclocal.m4,configure,Makefile.am,Makefile.in}
#- cargo build --verbose --all
- git status
- cargo package -vv --manifest-path=harfbuzz-sys/Cargo.toml
- diff src*.txt || true
- diff util*.txt || true
- diff -r harfbuzz-sys/harfbuzz target/package/harfbuzz-sys-0.3.1/harfbuzz || true
# Run the ctest-generated tests
#- cargo run --manifest-path=harfbuzz-sys-test/Cargo.toml
