language: rust
sudo: false

env:
  global:
    - RAGEL_PATH=$HOME/bin/ragel

addons:
  apt:
    packages:
      - strace

matrix:
  include:
  - os: linux
    rust: stable
    env: HARFBUZZ_SYS_NO_PKG_CONFIG="0"
  - os: linux
    rust: stable
    env: HARFBUZZ_SYS_NO_PKG_CONFIG="1"
  - os: linux
    rust: nightly
  #- os: osx
  #  rust: stable

before_script:
  - which ragel && ragel -v || true
  - mkdir -p $HOME/bin
  - echo '#!/bin/true' > $RAGEL_PATH
  - chmod u+x $RAGEL_PATH && [[ "$(which ragel)" == "$RAGEL_PATH" ]]

script:
#- touch harfbuzz-sys/harfbuzz/{configure.ac,aclocal.m4,configure,Makefile.am,Makefile.in}
#- cargo build --verbose --all
- git status
- strace -f -t -o strace.out -e trace=file cargo package -vv --manifest-path=harfbuzz-sys/Cargo.toml
- grep "/home/travis/build/spl/rust-harfbuzz/target/package/harfbuzz-sys-0.3.1/harfbuzz" strace.out
- diff src*.txt || true
- diff util*.txt || true
- diff -r harfbuzz-sys/harfbuzz target/package/harfbuzz-sys-0.3.1/harfbuzz || true
# Run the ctest-generated tests
#- cargo run --manifest-path=harfbuzz-sys-test/Cargo.toml
