[package]
name = "harfbuzz-sys"
version = "0.3.0"

authors = ["The Servo Project Developers"]
license = "MIT"

description = "Rust bindings to the HarfBuzz text shaping engine"
repository = "https://github.com/servo/rust-harfbuzz"
documentation = "https://docs.rs/harfbuzz-sys/"
keywords = ["opentype", "font", "text", "layout", "unicode"]
categories = ["external-ffi-bindings", "internationalization"]

links = "harfbuzz"
build = "build.rs"

[build-dependencies]
pkg-config = { version = "0.3", optional = true }
cmake = { version = "0.1", optional = true }

[target.'cfg(any(target_os = "android", all(unix, not(target_os = "macos"))))'.dependencies]
freetype = { version = "0.4", default-features = false }

[features]
default = ["build-native-harfbuzz", "build-native-freetype"]
build-native-harfbuzz = ["cmake", "pkg-config"]
build-native-freetype = ["freetype/build-native-freetype"]
