[package]
name = "harfbuzz-sys"
version = "0.1.5"

authors = ["The Servo Project Developers"]
license = "MIT"

description = "Rust bindings to the HarfBuzz text shaping engine"
repository = "https://github.com/servo/rust-harfbuzz"
documentation = "http://doc.servo.org/harfbuzz_sys/"
keywords = ["opentype", "font", "text", "layout", "unicode"]

links = "harfbuzz"
build = "build.rs"

[dependencies]
libc = "0.2"

[build-dependencies]
pkg-config = "0.3"
cmake = "0.1"
