[package]
name = "harfbuzz-sys"
version = "0.2.1"

authors = ["The Servo Project Developers"]
license = "MIT"

description = "Rust bindings to the HarfBuzz text shaping engine"
repository = "https://github.com/servo/rust-harfbuzz"
documentation = "https://docs.rs/harfbuzz-sys/"
keywords = ["opentype", "font", "text", "layout", "unicode"]

links = "harfbuzz"
build = "build.rs"

[build-dependencies]
pkg-config = "0.3"
cmake = "0.1"

[target.'cfg(any(target_os = "android", all(unix, not(target_os = "macos"))))'.dependencies]
freetype = "0.4"
